// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IPlayerService is an autogenerated mock type for the IPlayerService type
type IPlayerService struct {
	mock.Mock
}

// GetScores provides a mock function with given fields: ctx, player1Name, player2Name
func (_m *IPlayerService) GetScores(ctx context.Context, player1Name string, player2Name string) (string, error) {
	ret := _m.Called(ctx, player1Name, player2Name)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, player1Name, player2Name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, player1Name, player2Name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
